### ISSUE TITLE
If source file is missing, error is thrown but resource shows success

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-mount_iso#3]
If the mount_iso resource attempts to mount an ISO file which doesn't exist, an error is logged in the debug output but the resource still returns a success.  This should not be the intended behaviour.

**Comment by glennsarti** [comment]
https://github.com/puppetlabs/puppetlabs-mount_iso/pull/9

**Comment by michaeltlombardi** [comment]
Closed by #9.
